### ISSUE TITLE
Adding more Dockerfiles

### ISSUE THREAD

**Issue by bmpvieira** [yeban/switch#11]
I've tried to add ubuntu and centos (#8) but using switch causes:
```bash
exec: "bmpvieira": executable file not found in $PATHFATA[0000] Error response from daemon: Cannot start container 1e9ae17ba307d88500b23f73b49aaeec3e98c65ffe85ebfd8f2dfb70a100f690: exec: "bmpvieira": executable file not found in $PATH
```

Maybe I missed something very simple.

**Comment by yeban** [comment]
They need to inherit `FROM switch/baseimage`.

**Comment by bmpvieira** [comment]
So currently you can only add Ubuntu based distros?

**Comment by yeban** [comment]
Yeah.

**Comment by yeban** [comment]
Closing for the same reason as #8. Please open a new issue if a particular image fails to work with switch.
