### ISSUE TITLE
Add ubuntu and centos with minimal config

### ISSUE THREAD

**Issue by bmpvieira** [yeban/switch#8]
Bio-linux takes all eternity to build because it installs many bioinformatics packages and dependencies. Switch should provide other lighter Dockerfiles for quick testing, like Ubuntu and CentOS.

**Comment by yeban** [comment]
You can `switch baseimage`. 'baseimage' is not shown in the output of `switch -l`, but is there for testing and other images to inherit from (at least till we have considered another approach). 'baseimage' is essentially ubuntu 14.04.1 - https://github.com/yeban/switch/tree/master/Dockerfiles/baseimage

**Comment by yeban** [comment]
With #12 done, you can theoretically use any image now - have tested with a few. There will be caveats with some - will improve there with time.
